name: CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: 'false'
          fetch-depth: 0  # Untuk mendapatkan semua history tag
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Build artifacts
        run: |
          npm run build:prod:zip:chrome
          npm run build:prod:zip:edge
          npm run build:prod:zip:firefox
          npm run build:prod:zip:opera
        env:
          BUSTER_SECRETS: ${{ secrets.BUSTER_SECRETS }}
      
      - name: Generate version info
        id: version
        run: |
          # Mendapatkan versi dari package.json
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
      
      - name: Hash artifacts
        run: |
          cd artifacts
          find . -type f -name '*.zip' -exec sha256sum {} \; > SHA256SUMS.txt
        if: startsWith(github.ref, 'refs/tags/v')
      
      - name: Create download index
        run: |
          # Buat file index.html untuk memudahkan download
          cat <<EOF > artifacts/index.html
          <html><body>
          <h1>Build Artifacts - ${{ steps.version.outputs.version }}</h1>
          <ul>
          $(cd artifacts; find . -type f -name '*.zip' -exec echo '<li><a href="{}">{}</a></li>' \;)
          <li><a href="SHA256SUMS.txt">SHA256 Checksums</a></li>
          </ul>
          <p>Build date: $(date)</p>
          </body></html>
          EOF
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: browser-extensions
          path: artifacts/
          retention-days: 7
        if: success()
  
  release:
    name: Release on GitHub
    runs-on: ubuntu-22.04
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: browser-extensions
          path: artifacts/
      
      - name: Verify checksums
        run: |
          cd artifacts
          sha256sum -c SHA256SUMS.txt
      
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Version ${{ github.ref_name }}"
          body: |
            ## Browser Extensions
            
            Download the extension for your browser:
            
            - [Chrome Extension](artifacts/buster-chrome.zip)
            - [Firefox Extension](artifacts/buster-firefox.zip)
            - [Edge Extension](artifacts/buster-edge.zip)
            - [Opera Extension](artifacts/buster-opera.zip)
            
            [Verify SHA256 Checksums](artifacts/SHA256SUMS.txt)
            
            ## Changelog
            [View complete changelog](https://github.com/dessant/buster/blob/main/CHANGELOG.md#changelog)
          files: artifacts/*.*
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
      
      - name: Upload to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./artifacts
          keep_files: true
          destination_dir: builds
